### PR TITLE
Reviewers

### PR DESCRIPTION
**Pull request by maelle**
cf https://github.com/ropensci/roregistry/issues/27

### CODE REVIEW

**Comment by maelle** [comment]
@sckott note that you need an `AIRTABLE_API_KEY` variable in .Renviron.

**Comment by sckott** [comment]
so how do  you test this?

**Comment by maelle** [comment]
On the server 😢

**Comment by maelle** [comment]
I have not tested it, if you can't, tomorrow I'll look for the login info.

**Comment by sckott** [comment]
sorry I seem to have forgotten about this - should we still merge this? or have things changed?

**Pull request closed without merging**
